-- One-time cleanup: remove all feed posts that were generated by the old sim
-- tick / choice systems. Curated posts (synced from the R2 bucket) carry a
-- source_key and survive; everything else was engine noise. The feed is now
-- fed exclusively by the R2 image+caption sync job.
DELETE FROM character_posts WHERE source_key IS NULL;
