-- RETIRED (was destructive on every deploy).
--
-- This file once ran `DELETE FROM character_posts WHERE source_key IS NULL;` as a
-- one-time cleanup of old engine-generated posts. But the migration runner had no
-- "already applied" ledger and re-ran every file on each deploy, so this DELETE
-- wiped ALL generated/dynamic posts (including the autonomous character posts,
-- which legitimately have source_key = NULL) on every push.
--
-- The feed is now intentionally fed by autonomous character posts again, so this
-- cleanup must NOT run anymore. Neutralized to a harmless no-op. A schema_migrations
-- ledger (see db/migrate.ts) now ensures each migration runs at most once.
SELECT 1;
